language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: g7bpAQzjpLPEPGV8pVlVdl61IRdZaE4x2cBLQEZ/wmYeUnshUY/+42KBLwHEyUkXPmS4SozF+hqlIXRdLtWEmzb2s30SN3hE33sPEUpKIC75yrhujkbn8S3EiR8kI1/QoOBiVU8KJMAhpJqYgOm0yjdD8YB40QN/b8W4vLDUTkUTmzZOrVNcMEUAmr5923/KkUxmg7UyTVUlQg+KBkEZEJ6oTWE7q6hP8/qKCqTzkmtMCtLkFfSZne9JMqrtyp+OFCr86NefnMhxTlfnvzhYetDTiIMi7eXQVIwsL3uakKg6DmbVFVCOlyUS0H/W8BSA/Slf/siY3hjoFxcnDYjVYoZi2RLETBf9Ca2iBCHoSeSEptjtyHYCJOIjPsgG9wtmjeK8WSPzSVSlymT1nVNnTI5kH7BFIUBs+gFHEt7tsDxG/MObpH9tJhx1rt30G7hxlJN3h3Yy6hadImIxsK7OEsGPLRyNkLgzrkC+f+7uZFiVsTVyXpB+vvPo5nPgsoVE++qj2GWG6DkfnRKJVkPe+52MXRJCi0yL/NMDhnCwrl0JSvZuVzgwAH76LwQ5k/c6WwbBqD998qXHtPYaUb5yDvpxsJqv+V9PDGauV48Apfdd51KViuXU8Qq2ojFJNIVhlAZ4HzggQzXHeQ3rAUxUstIdZfy3IaIGUA/8eW+hEjs=
  app: trello-test-tks
  on:
    repo: tkshehan/react-trello-testing
