language: node_js
node_js:
- stable
- '6'
- '4'
deploy:
  provider: heroku
  api_key:
    secure: gmsTVoWfnBTIhL0ajnikM5dzc1yURPOVyObArUxohC+F26WU4muY+tgsmuSEAu46wzQNbeTXxev8t6aZqHu649/XTlqFWBAYfxyi2mjYijxbf007OlXR/QEtJnptk//GiSsdwTGyjZC9bY4dpDi6SWXTG0YOzgZZD0WUc2PHBEVEwf5SV8FxvjAGl/Py2/jspkuMVC3hvS3NdY6BfgeaOb3ZeXCcbQ5n1d1oqzj4DzV1+skgQsGQdoBwzyJd3b6sfZk8Km/dUa7Z068Y3EhYHEgzi1+8Pi6p7h7Bz43K7vEF+qnB5pgIl28BckyE1uuwmeXG08wrlBwevGFnMpEEA3ECIa2/iKq58juHoFC9S0N+7ZrAhipFmMOqv1iY1NsQoTj6ADukgWeMAkhfuKNKR45s3lwvFhceyxNCS7vFS3hhGUr7gtW7LOR59VabBJkn3QkdXPuH3OTncI99gt/GDHRTFBwSvNWxjOLMsUDil0qAmsza/cVN1361BKT6OY8DD7fHeV1JET8V2G5Q48Bu60AuY5/ASQ3kI8BTOK7Edg/3on8Q0p9dHwvOxBWISMkczLkDnhz0F9JiAA3SN32/jWHKGhuRzLRaYZtJlq2m2mdvTREovxp55dt1ZimH4Blmf9i6gb1s0T0OM1vf/p89pgLK6pHBSMBPzYXBskzzJi4=
  app: react-trello-testing-tks
  on:
    repo: tkshehan/react-trello-testing
